### ISSUE TITLE
Add CSRF check

### ISSUE THREAD

**Issue by PVince81** [noveens/cors#1]
To protect against XSS.

See https://github.com/noveens/cors/blob/master/lib/Controller/SettingsController.php#L66.

You'll need your forms to contain a value "requesttoken" which you can pick from the JS `OC.requestToken`. There is also likely a PHP way but need to check in core how others do it...

**Comment by noveens** [comment]
Fixed : https://github.com/noveens/cors/commit/5e793bf845806bccec5c086cf51f9e1d586ca557
