### ISSUE TITLE
Use app framework param injection

### ISSUE THREAD

**Issue by PVince81** [noveens/cors#2]
Don't access global variables here: https://github.com/noveens/cors/blob/master/lib/Controller/SettingsController.php#L83

In general using global variables anywhere is frowned upon.

Add an argument `$domain` to `addDomain()` and the app framework will automatically inject the value there for you to use.

**Comment by noveens** [comment]
Fixed : https://github.com/noveens/cors/commit/5e793bf845806bccec5c086cf51f9e1d586ca557
